fix: LPS-134687
liferay/liferay-ckeditor pull request #181
Opened 2021-06-23 19:27 UTC by fortunatomaldonado

https://issues.liferay.com/browse/LPS-134687
https://github.com/liferay/liferay-ckeditor/issues/180

When we switched to CodeMirror, right clicking in Source view no longer worked. By adding `cke_enable_context_menu` to the editor, we are now able to right click.

Let me know if there are any questions or comments about this.
Thank you.

2021-06-25 09:11 UTC, julien commented on plugins/codemirror/plugin.js
> +				);
@fortunatomaldonado you can also get a reference to this element with

```js
instance.codeMirrorEditor.getWrapperElement();
```

Which returns the `<div>` element directly and avoids having to deal with an `HTMLCollection`
If you'd rather like a `CKEDITOR.dom.element` object, you can also use 

```js
editableParent.findOne('.CodeMirror');
```

2021-06-25 09:12 UTC, julien commented
@fortunatomaldonado I fetched this branch, made a debug build and tried in dxp but unfortunately I still don't see CKEDITOR's context menu in "source mode" - do you have any screenshots of this working? Thanks

2021-06-25 09:13 UTC, julien requested changes
Let's use CodeMirror or CKEDITOR's methods to get a reference to elements

2021-06-25 16:29 UTC, fortunatomaldonado commented
Hello @julien,

Thank you for taking a look at this! I will make the updates.

I attached a video with the context menu appearing. Let me know what you think.

https://user-images.githubusercontent.com/31672551/123456583-dbd6d680-d597-11eb-8be8-6ee513a2f908.mp4

2021-06-28 06:23 UTC, julien commented
@fortunatomaldonado When reading the ticket, I thought we wanted to show CKEditor's custom context menu, and not the browser's native context menu. After doing a build, I can see this working as we expect it to, and the code change seems reasonable to me, so I approve this pull request. Thanks!

2021-06-28 06:29 UTC, merged

2021-06-28 22:44 UTC, fortunatomaldonado commented
Hello @julien,

I apologize for not being clear in the ticket of the issue and I will try to be more clear moving forward.
Thank you for the help with this!

2021-06-29 06:33 UTC, julien commented
Hey @fortunatomaldonado,
No problem at all - it's totally normal for these things to happen, you did great.